[
  { "id": "V001", "name": "Ashwagandha Capsules", "description": "Stress relief and immunity booster.", "price": 450.0, "category": "Vati (Tablets)" },
  { "id": "V002", "name": "Brahmi Vati", "description": "Enhances memory and mental clarity.", "price": 320.0, "category": "Vati (Tablets)" },
  { "id": "V003", "name": "Chandraprabha Vati", "description": "Supports kidney and urinary health.", "price": 285.0, "category": "Vati (Tablets)" },
  { "id": "V004", "name": "Kanchanar Guggulu", "description": "Effective for thyroid and glands.", "price": 360.0, "category": "Vati (Tablets)" },
  { "id": "V005", "name": "Arogyavardhini Vati", "description": "Supports liver function and digestion.", "price": 240.0, "category": "Vati (Tablets)" },
  { "id": "V006", "name": "Gokshuradi Guggulu", "description": "Promotes healthy urinary tract.", "price": 290.0, "category": "Vati (Tablets)" },
  { "id": "V007", "name": "Triphala Guggulu", "description": "Detoxification and weight management.", "price": 275.0, "category": "Vati (Tablets)" },
  { "id": "V008", "name": "Punarnavadi Vati", "description": "Reduces edema and supports kidneys.", "price": 310.0, "category": "Vati (Tablets)" },
  { "id": "V009", "name": "Sarpagandha Vati", "description": "Helps manage blood pressure.", "price": 420.0, "category": "Vati (Tablets)" },
  { "id": "V010", "name": "Shankha Vati", "description": "Relieves gas and abdominal pain.", "price": 190.0, "category": "Vati (Tablets)" },
  { "id": "V011", "name": "Eladi Vati", "description": "Relief for sore throat and cough.", "price": 180.0, "category": "Vati (Tablets)" },
  { "id": "V012", "name": "Khadiradi Vati", "description": "Effective for mouth ulcers and throat.", "price": 150.0, "category": "Vati (Tablets)" },
  { "id": "V013", "name": "Lashunadi Vati", "description": "Improves digestion and reduces gas.", "price": 165.0, "category": "Vati (Tablets)" },
  { "id": "V014", "name": "Rajahpravartini Vati", "description": "Supports female menstrual health.", "price": 340.0, "category": "Vati (Tablets)" },
  { "id": "V015", "name": "Vyoshadi Vati", "description": "Classical remedy for rhinitis and cold.", "price": 210.0, "category": "Vati (Tablets)" },
  { "id": "V016", "name": "Bilwadi Vati", "description": "Effective for diarrhea and food poisoning.", "price": 225.0, "category": "Vati (Tablets)" },
  { "id": "V017", "name": "Sanjivani Vati", "description": "Immunity support for chronic fevers.", "price": 195.0, "category": "Vati (Tablets)" },
  { "id": "C001", "name": "Triphala Churna", "description": "Classical digestive support.", "price": 180.0, "category": "Churna (Powder)" },
  { "id": "C002", "name": "Sitopaladi Churna", "description": "Relief for cough and cold.", "price": 220.0, "category": "Churna (Powder)" },
  { "id": "C003", "name": "Avipattikar Churna", "description": "Helps with hyperacidity.", "price": 210.0, "category": "Churna (Powder)" },
  { "id": "C004", "name": "Amalaki Churna", "description": "Pure Vitamin C for immunity.", "price": 160.0, "category": "Churna (Powder)" },
  { "id": "C005", "name": "Mulethi Churna", "description": "Soothes throat and ulcers.", "price": 140.0, "category": "Churna (Powder)" },
  { "id": "C006", "name": "Shatavari Churna", "description": "Hormonal balance for women.", "price": 380.0, "category": "Churna (Powder)" },
  { "id": "C007", "name": "Ajwain Churna", "description": "Relieves bloating and gas.", "price": 120.0, "category": "Churna (Powder)" },
  { "id": "C008", "name": "Neem Churna", "description": "Blood purifier and skin support.", "price": 170.0, "category": "Churna (Powder)" },
  { "id": "C009", "name": "Haritaki Churna", "description": "Mild laxative and detoxifier.", "price": 150.0, "category": "Churna (Powder)" },
  { "id": "C010", "name": "Talisadi Churna", "description": "Support for lung and respiratory health.", "price": 240.0, "category": "Churna (Powder)" },
  { "id": "C011", "name": "Hingwashtak Churna", "description": "Best for indigestion and low appetite.", "price": 190.0, "category": "Churna (Powder)" },
  { "id": "C012", "name": "Trikatu Churna", "description": "Metabolism booster and sinus relief.", "price": 165.0, "category": "Churna (Powder)" },
  { "id": "C013", "name": "Pushyanuga Churna", "description": "Supports gynecological health.", "price": 320.0, "category": "Churna (Powder)" },
  { "id": "C014", "name": "Sudarshan Churna", "description": "Fever management and detox.", "price": 250.0, "category": "Churna (Powder)" },
  { "id": "C015", "name": "Yashtimadhu Churna", "description": "Licorice root for gastric relief.", "price": 145.0, "category": "Churna (Powder)" },
  { "id": "L001", "name": "Dashmularishta", "description": "Nervine tonic and post-natal care.", "price": 550.0, "category": "Arishta (Liquid)" },
  { "id": "L002", "name": "Abhayarishta", "description": "Constipation and digestive support.", "price": 420.0, "category": "Arishta (Liquid)" },
  { "id": "L003", "name": "Ashokarishta", "description": "Uterine tonic for women.", "price": 480.0, "category": "Arishta (Liquid)" },
  { "id": "L004", "name": "Kumaryasava", "description": "Liver tonic and anemia support.", "price": 390.0, "category": "Arishta (Liquid)" },
  { "id": "L005", "name": "Arjunarishta", "description": "Heart and cardiovascular health.", "price": 450.0, "category": "Arishta (Liquid)" },
  { "id": "L006", "name": "Lohasava", "description": "Iron supplement and liver support.", "price": 360.0, "category": "Arishta (Liquid)" },
  { "id": "L007", "name": "Khadirarishta", "description": "Relief for skin diseases.", "price": 410.0, "category": "Arishta (Liquid)" },
  { "id": "L008", "name": "Drakshasava", "description": "Appetite and strength booster.", "price": 490.0, "category": "Arishta (Liquid)" },
  { "id": "L009", "name": "Punarvasava", "description": "Kidney and urinary support.", "price": 380.0, "category": "Arishta (Liquid)" },
  { "id": "L010", "name": "Saraswatarishta", "description": "Memory and focus enhancement.", "price": 520.0, "category": "Arishta (Liquid)" },
  { "id": "L011", "name": "Chandanasava", "description": "Cooling tonic for burning sensation.", "price": 460.0, "category": "Arishta (Liquid)" },
  { "id": "L012", "name": "Vidangarishta", "description": "Expels intestinal worms and parasites.", "price": 380.0, "category": "Arishta (Liquid)" },
  { "id": "L013", "name": "Kutajarishta", "description": "Management of dysentery and IBS.", "price": 340.0, "category": "Arishta (Liquid)" },
  { "id": "L014", "name": "Kanakasava", "description": "Respiratory support for asthma/cough.", "price": 410.0, "category": "Arishta (Liquid)" },
  { "id": "L015", "name": "Balarishta", "description": "Nervine tonic and physical strength.", "price": 470.0, "category": "Arishta (Liquid)" },
  { "id": "O001", "name": "Maha Narayan Taila", "description": "Joint and muscle pain relief oil.", "price": 650.0, "category": "Taila (Oil)" },
  { "id": "O002", "name": "Bhringraj Oil", "description": "Hair growth and scalp health.", "price": 480.0, "category": "Taila (Oil)" },
  { "id": "O003", "name": "Anu Taila", "description": "Nasal drops for sinus and headache.", "price": 150.0, "category": "Taila (Oil)" },
  { "id": "O004", "name": "Kshirabala Taila", "description": "Nervous system and arthritis support.", "price": 590.0, "category": "Taila (Oil)" },
  { "id": "O005", "name": "Dhanwantharam Taila", "description": "Post-natal and neuromuscular relief.", "price": 620.0, "category": "Taila (Oil)" },
  { "id": "O006", "name": "Kumkumadi Tailam", "description": "Premium facial oil for glow and spots.", "price": 1250.0, "category": "Taila (Oil)" },
  { "id": "O007", "name": "Jatyadi Taila", "description": "Healing oil for wounds and ulcers.", "price": 280.0, "category": "Taila (Oil)" },
  { "id": "O008", "name": "Shadbindu Taila", "description": "Nasal support for sinusitis.", "price": 170.0, "category": "Taila (Oil)" },
  { "id": "O009", "name": "Pinda Taila", "description": "Relief for gout and burning pain.", "price": 310.0, "category": "Taila (Oil)" },
  { "id": "O010", "name": "Karpooradi Taila", "description": "Muscle cramps and chest congestion.", "price": 240.0, "category": "Taila (Oil)" },
  { "id": "O011", "name": "Murivenna", "description": "Healing oil for fractures and sprains.", "price": 320.0, "category": "Taila (Oil)" },
  { "id": "O012", "name": "Sahacharadi Taila", "description": "Effective for varicose veins/leg pain.", "price": 450.0, "category": "Taila (Oil)" },
  { "id": "O013", "name": "Eladi Tailam", "description": "Treats skin allergies and itching.", "price": 490.0, "category": "Taila (Oil)" },
  { "id": "O014", "name": "Balaashwagandhadi Taila", "description": "Muscle wasting and nerve weakness.", "price": 550.0, "category": "Taila (Oil)" },
  { "id": "O015", "name": "Neelibringadi Oil", "description": "Deep nourishment for hair loss.", "price": 510.0, "category": "Taila (Oil)" },
  { "id": "G001", "name": "Pure Himalayan Shilajit", "description": "Energy, stamina, and mineral support.", "price": 1850.0, "category": "Premium" },
  { "id": "G002", "name": "Chyawanprash Special", "description": "Daily immunity booster with 40+ herbs.", "price": 750.0, "category": "Premium" },
  { "id": "G003", "name": "Brahmi Ghrita", "description": "Ghee-based brain and memory tonic.", "price": 720.0, "category": "Ghrita" },
  { "id": "G004", "name": "Panchatikta Ghrita", "description": "Skin and blood purification support.", "price": 680.0, "category": "Ghrita" },
  { "id": "G005", "name": "Saraswata Ghrita", "description": "Enhances speech and intelligence.", "price": 740.0, "category": "Ghrita" },
  { "id": "G006", "name": "Triphala Ghrita", "description": "Excellent for eye health and vision.", "price": 650.0, "category": "Ghrita" },
  { "id": "G007", "name": "Dadimadi Ghrita", "description": "Iron absorption and anemia support.", "price": 590.0, "category": "Ghrita" },
  { "id": "G008", "name": "Guggulutiktaka Ghrita", "description": "Joint, skin, and bone nourishment.", "price": 780.0, "category": "Ghrita" },
  { "id": "G009", "name": "Jatyadi Ghrita", "description": "Heals deep-seated ulcers and wounds.", "price": 420.0, "category": "Ghrita" },
  { "id": "G010", "name": "Mahatiktaka Ghrita", "description": "Advanced blood purification support.", "price": 850.0, "category": "Ghrita" },
  { "id": "B001", "name": "Abhrak Bhasma", "description": "Rejuvenator for respiratory health.", "price": 950.0, "category": "Bhasma (Mineral)" },
  { "id": "B002", "name": "Godanti Bhasma", "description": "Natural calcium for headaches/fever.", "price": 180.0, "category": "Bhasma (Mineral)" },
  { "id": "B003", "name": "Mukta Shukti Bhasma", "description": "Cooling relief for acidity/ulcers.", "price": 240.0, "category": "Bhasma (Mineral)" },
  { "id": "B004", "name": "Shankha Bhasma", "description": "Classical remedy for abdominal pain.", "price": 160.0, "category": "Bhasma (Mineral)" },
  { "id": "B005", "name": "Swarna Makshik Bhasma", "description": "Supports iron levels and energy.", "price": 380.0, "category": "Bhasma (Mineral)" },
  { "id": "B006", "name": "Yashad Bhasma", "description": "Natural Zinc for immunity and eyes.", "price": 310.0, "category": "Bhasma (Mineral)" },
  { "id": "B007", "name": "Mandur Bhasma", "description": "Potent iron support for anemia.", "price": 270.0, "category": "Bhasma (Mineral)" },
  { "id": "B008", "name": "Praval Pishti", "description": "Calcium supplement from Coral.", "price": 520.0, "category": "Bhasma (Mineral)" },
  { "id": "B009", "name": "Akik Pishti", "description": "Heart tonic and brain calmer.", "price": 440.0, "category": "Bhasma (Mineral)" },
  { "id": "B010", "name": "Kapardak Bhasma", "description": "Digestive aid for heavy feeling.", "price": 140.0, "category": "Bhasma (Mineral)" },
  { "id": "K001", "name": "Maharasnadi Kwath", "description": "Concentrated decoction for arthritis.", "price": 580.0, "category": "Kwath (Decoction)" },
  { "id": "K002", "name": "Dashmool Kwath", "description": "Body pain and inflammatory relief.", "price": 420.0, "category": "Kwath (Decoction)" },
  { "id": "K003", "name": "Varunadi Kwath", "description": "Kidney stone and urinary support.", "price": 490.0, "category": "Kwath (Decoction)" },
  { "id": "K004", "name": "Pathyadi Kwath", "description": "Relieves migraine and headaches.", "price": 310.0, "category": "Kwath (Decoction)" },
  { "id": "K005", "name": "Sudarshan Kwath", "description": "Best for viral and seasonal fevers.", "price": 350.0, "category": "Kwath (Decoction)" },
  { "id": "K006", "name": "Gandharvahastadi Kwath", "description": "Gentle detox and digestive aid.", "price": 380.0, "category": "Kwath (Decoction)" },
  { "id": "K007", "name": "Manjishtadi Kwath", "description": "Blood purifier for skin glowing.", "price": 450.0, "category": "Kwath (Decoction)" },
  { "id": "K008", "name": "Punarnavadi Kwath", "description": "Reduces water retention and edema.", "price": 410.0, "category": "Kwath (Decoction)" },
  { "id": "K009", "name": "Rasnadi Kwath", "description": "Nerve and lower back pain relief.", "price": 390.0, "category": "Kwath (Decoction)" },
  { "id": "K010", "name": "Nimbadi Kwath", "description": "Antiseptic decoction for skin.", "price": 320.0, "category": "Kwath (Decoction)" },
  { "id": "S001", "name": "Livo-Care Syrup", "description": "Daily liver detox and appetite.", "price": 280.0, "category": "Syrup" },
  { "id": "S002", "name": "Kof-Mukt Syrup", "description": "Non-drowsy herbal cough relief.", "price": 190.0, "category": "Syrup" },
  { "id": "S003", "name": "Hempo-Rich Syrup", "description": "Natural iron and blood booster.", "price": 320.0, "category": "Syrup" },
  { "id": "S004", "name": "Brain-Power Syrup", "description": "Memory and concentration for kids.", "price": 350.0, "category": "Syrup" },
  { "id": "S005", "name": "Digest-O Syrup", "description": "Instant relief from gas and bloating.", "price": 180.0, "category": "Syrup" },
  { "id": "S006", "name": "Tulsi Tulsi Drops", "description": "Concentrated 5-species Tulsi extract.", "price": 210.0, "category": "Syrup" },
  { "id": "S007", "name": "Giloy Satva Juice", "description": "High-potency immunity booster.", "price": 450.0, "category": "Syrup" },
  { "id": "S008", "name": "Amla Pure Juice", "description": "Cold-pressed Vitamin C booster.", "price": 380.0, "category": "Syrup" },
  { "id": "S009", "name": "Aloe Vera Fiber Juice", "description": "Skin glow and bowel regularity.", "price": 420.0, "category": "Syrup" },
  { "id": "S010", "name": "Karela Jamun Juice", "description": "Blood sugar management formula.", "price": 490.0, "category": "Syrup" }
]
